### ISSUE TITLE
1.18 version 1.2 of the worldborderfixer mod prevents startup with following error

### ISSUE THREAD

**Issue by Microjett** [GalievDev/worldborderfixer-unofficial#1]
1.18.2 version 1.2 of the worldborderfixer mod prevents startup with following error

`[10Feb2024 17:36:17.560] [main/FATAL] [net.minecraftforge.forgespi.language.MavenVersionAdapter/]: Failed to parse version spec [40)
org.apache.maven.artifact.versioning.InvalidVersionSpecificationException: Single version must be surrounded by []: [40)`

This was found when starting up a Create Arcane Engineering server. 

Replaced the mod with the 1.1 version and the server started OK.

**Comment by Microjett** [comment]
Appreciate your efforts in providing this fix for Forge!

**Comment by GalievDev** [comment]
it will be fixed soon.

**Comment by GalievDev** [comment]
Fixed - https://modrinth.com/mod/worldborderfixer-unofficial/version/bPWQTa4S
