### ISSUE TITLE
After rejoin the world, World border has been reseted.

### ISSUE THREAD

**Issue by AngleNaris** [GalievDev/worldborderfixer-unofficial#2]
Mod version is 2024.1.2
Forge version is 47.2.20
Minecraft 1.20.1
-------------------------
No error log in console
-------------------------
I tested with 2 mods:
Overworld Mirror
PerDimension Game Rules

remove PerDimension Game Rules still have same issue.

**Comment by mikaba-eu** [comment]
same issue by us, we play ATM 8 and use this mod (1.19.2) after restart the server, all worldborders get reseting.

**Comment by GalievDev** [comment]
Sorry for the late reply, I'll check it out later on my own time

**Comment by GalievDev** [comment]
Already done: https://modrinth.com/mod/worldborderfixer-unofficial/versions

**Comment by killbot24** [comment]
Can you fix it on 1.18.2?
