### ISSUE TITLE
Doesnt seem to work on version 1.20.1

### ISSUE THREAD

**Issue by OzTheM9** [GalievDev/worldborderfixer-unofficial#4]
I have the mod(worldborderfixer-2024.5.2 (1.20).jar) installed on our All the mods 9 server and it doesnt seem to work. there are no errors in the console at all. It just doesnt do per dimension world borders, but keeps the old system. I'd like to post the log, but the mod has no messages present in it.

**Comment by GalievDev** [comment]
I just forgot add refmap for mixins 😅
Try new version - https://modrinth.com/mod/worldborderfixer-unofficial/version/o3YUEcyG
